const Router = require('express')
const router = new Router()
const deviceRouter = require('./deviceRouter')
const userRouter = require('./userRouter')
const brandRouter = require('./brandRouter')
const typeRouter = require('./typeRouter')
const companyAdminRouter = require('./companyAdminRouter')
const cointRouter = require('./coinsRouter')

router.use('/user', userRouter)
router.use('/type', typeRouter)
router.use('/brand', brandRouter)
router.use('/device', deviceRouter)
router.use('/comAdmin', companyAdminRouter)
router.use('/coint', cointRouter)
module.exports = router
